import { Box, Button, Heading, Text, VStack } from "@chakra-ui/react";
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import CsvImport from "../features/csv-import/CsvImport";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>2bttns</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack alignItems="center" width="100%" height="100%" as="main">
        <Heading size="4xl">
          Your{" "}
          <Text color="blue.500" display="inline">
            2bttns
          </Text>{" "}
          App
        </Heading>

        <Box>
          <Text>
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </Text>
          <AuthShowcase />

          <CsvImport />
        </Box>
      </VStack>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <Box>
      <Text>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </Text>
      <Button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </Box>
  );
};
