version: "3.9"

services:
  dev-db:
    image: postgres:13
    restart: always
    container_name: integration-dev-db-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-pass
      POSTGRES_DB: dev-db
  test-db:
    image: postgres:13
    restart: always
    container_name: integration-test-db-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
      POSTGRES_DB: test-db
