import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import { twobttns } from "./utils/2bttns";

export default function Home() {
  const redirectToGame = () => {
    if (typeof window === "undefined") {
      return;
    }
    const game_id = window.prompt("Enter game id");
    if (!game_id) return;
    const user_id = window.prompt(
      "Enter user id (random strings are fine for now)"
    );
    if (!user_id) return;
    let num_items: any = window.prompt(
      "Enter #items (ALL for all items; or leave blank to use the configured default)"
    );

    const queryParams = new URLSearchParams();
    queryParams.append("game_id", game_id);
    queryParams.append("user_id", user_id);
    if (num_items) {
      if (num_items.toUpperCase() === "ALL") {
        num_items = "ALL";
      } else if (!isNaN(parseInt(num_items))) {
        num_items = parseInt(num_items);

        if (num_items < 1) {
          window.alert(`Invalid value: num_items=${num_items}`);
          return;
        }
      } else {
        window.alert(`Invalid value: num_items=${num_items}`);
        return;
      }

      if (num_items) {
        queryParams.append("num_items", num_items);
      }
    }
    queryParams.append("callback_url", `${window.location.href}/results`);

    window.location.href = `/api/play2bttns?${queryParams.toString()}`;
  };

  const twobttnsPlayersQuery = useQuery({
    queryKey: ["players"],
    queryFn: async () => {
      const getPlayers = twobttns.api.path("/players").method("get").create();
      const players = await getPlayers({});
      return players.data.players;
    },
  });

  const twobttnsTagsQuery = useQuery({
    queryKey: ["tags"],
    queryFn: async () => {
      const getTags = twobttns.api.path("/tags").method("get").create();
      const players = await getTags({});
      return players.data.tags;
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={redirectToGame}>To Game</button>

        <h1>Players</h1>
        <pre>{JSON.stringify(twobttnsPlayersQuery.data, null, 2)}</pre>

        <h1>Tags</h1>
        <pre>{JSON.stringify(twobttnsTagsQuery.data, null, 2)}</pre>
      </main>
    </>
  );
}
