/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/example/hello": {
    /**
     * Say hello 
     * @description Say hello to the world
     */
    get: operations["query.example.hello"];
  };
  "/example/create": {
    /**
     * Create example 
     * @description Create an example object in the database
     */
    post: operations["mutation.example.create"];
  };
  "/example/getAll": {
    /**
     * Get all examples 
     * @description Get all examples
     */
    get: operations["query.example.getAll"];
  };
  "/example/getSecretMessage": {
    /**
     * Get secret message 
     * @description Get secret message
     */
    get: operations["query.example.getSecretMessage"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: {
    /** @description Error response */
    error: {
      content: {
        "application/json": {
          message: string;
          code: string;
          issues?: ({
              message: string;
            })[];
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  "query.example.hello": {
    /**
     * Say hello 
     * @description Say hello to the world
     */
    parameters?: {
      query?: {
        text?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            greeting: string;
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  "mutation.example.create": {
    /**
     * Create example 
     * @description Create an example object in the database
     */
    requestBody?: {
      content: {
        "application/json": {
          id?: string;
        };
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            id: string;
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  "query.example.getAll": {
    /**
     * Get all examples 
     * @description Get all examples
     */
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            examples: ({
                id: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              })[];
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  "query.example.getSecretMessage": {
    /**
     * Get secret message 
     * @description Get secret message
     */
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": string;
        };
      };
      default: components["responses"]["error"];
    };
  };
}
