/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/example/hello": {
    /**
     * Say hello 
     * @description Say hello to the world
     */
    get: operations["query.example.hello"];
  };
  "/example/create": {
    /**
     * Create example 
     * @description Create an example object in the database
     */
    post: operations["mutation.example.create"];
  };
  "/example/getAll": {
    /**
     * Get all examples 
     * @description Get all examples
     */
    get: operations["query.example.getAll"];
  };
  "/example/getSecretMessage": {
    /**
     * Get secret message 
     * @description Get secret message
     */
    get: operations["query.example.getSecretMessage"];
  };
  "/game-objects/ranked": {
    /**
     * Get Ranked Results 
     * @description Get ranked Game Object results for a player
     */
    get: operations["query.gameObjects.getRanked"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: {
    /** @description Error response */
    error: {
      content: {
        "application/json": {
          message: string;
          code: string;
          issues?: ({
              message: string;
            })[];
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  "query.example.hello": {
    /**
     * Say hello 
     * @description Say hello to the world
     */
    parameters?: {
      query?: {
        text?: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            greeting: string;
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  "mutation.example.create": {
    /**
     * Create example 
     * @description Create an example object in the database
     */
    requestBody?: {
      content: {
        "application/json": {
          id?: string;
        };
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            id: string;
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  "query.example.getAll": {
    /**
     * Get all examples 
     * @description Get all examples
     */
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            examples: ({
                id: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              })[];
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  "query.example.getSecretMessage": {
    /**
     * Get secret message 
     * @description Get secret message
     */
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": string;
        };
      };
      default: components["responses"]["error"];
    };
  };
  "query.gameObjects.getRanked": {
    /**
     * Get Ranked Results 
     * @description Get ranked Game Object results for a player
     */
    parameters: {
        /**
         * @description Specify input tags that will be used to score the game objects associated with the output tag.
         * 
         * If the output tag is included in the input tags, the player's score for those game object will be used as base scores
         */
        /** @description Specify the output tag of the game objects to get ranked results for */
      query: {
        playerId: string;
        inputTags: string;
        outputTag: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            scores: ({
                gameObject: {
                  id: string;
                  name: string;
                };
                score: number;
              })[];
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
}
